name: Workflow to get commit sha in GitHub actions

on:
  push:

jobs:
  display-commit-sha:
    runs-on: ubuntu-latest
    steps:
      - name: commit SHA of the head of the branch
        run: echo "The commit SHA is ${{ github.sha }}"