name: Electron Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build for Linux
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install pnpm
        run: npm i -g pnpm && pnpm config set node-linker hoisted

      - name: Install dependencies
        run: pnpm install

      - name: Build Electron app for Linux
        run: pnpm run make

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensamin-linux
          path: out/make/

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install pnpm
        run: npm i -g pnpm; pnpm config set node-linker hoisted

      - name: Install dependencies
        run: pnpm install

      - name: Build Electron app for Windows
        run: pnpm run make:windows

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensamin-windows
          path: out/make/

  build-macos:
    name: Build for MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install pnpm
        run: npm i -g pnpm && pnpm config set node-linker hoisted

      - name: Install dependencies
        run: pnpm install && pnpm install macos-alias ds-store appdmg electron-installer-dmg

      - name: Build Electron app for MacOS
        run: pnpm run make

      - name: Upload MacOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensamin-macos
          path: out/make/

  release:
    name: "Create Release"
    needs: [build-linux, build-windows, build-macos]
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: write
    steps:
      - name: Get version from repository
        uses: actions/checkout@v4

      - name: Set version from repository in environment
        id: get_version
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"

      - name: Download all build artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: ${{ env.PACKAGE_VERSION }} | Desktop Apps
          body: Automated release of desktop apps for version ${{ env.PACKAGE_VERSION }}
          tag_name: v${{ env.PACKAGE_VERSION }}-desktop-apps
          draft: false
          prerelease: false
          files: |
            ./artifacts/tensamin-linux/deb/x64/tensamin_${{ env.PACKAGE_VERSION }}_amd64.deb:tensamin-linux-x64-${{ env.PACKAGE_VERSION }}.deb
            ./artifacts/tensamin-windows/squirrel.windows/squirrel/Tensamin Setup ${{ env.PACKAGE_VERSION }}.exe:tensamin-windows-x64-${{ env.PACKAGE_VERSION }}.exe
            ./artifacts/tensamin-macos/zip/darwin/arm64/Tensamin-darwin-arm64-${{ env.PACKAGE_VERSION }}.zip:tensamin-macos-arm64-${{ env.PACKAGE_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aur-package:
    name: Create AUR Package
    needs: release
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Create Arch Linux Package
        run: pnpm run make:archlinux

      - name: Publish Arch Linux Package
        uses: ulises-jeremias/github-actions-aur-publish@v1
        with:
          pkgname: tensamin-bin
          pkgbuild: ./tensamin-aur/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Automated Update
          ssh_keyscan_types: ed25519
          update_pkgver: false